spring.application.name=courses_api

# Database

spring.datasource.url=jdbc:postgresql://localhost:5432/courses_api
spring.datasource.username=docker
spring.datasource.password=docker
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tokens 

security.token=${SECURITY_TOKEN}

security.key.public=${SECURITY_KEY_PUBLIC}

security.key.private=${SECURITY_KEY_PRIVATE}

token.sonar=${TOKEN_SONAR}

# Monitoring

management.endpoints.access.default=unrestricted
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.access=read-only
management.endpoint.health.show-details=always
management.endpoint.metrics.access=read-only
management.endpoint.prometheus.access=read-only